### ISSUE TITLE
Trouble importing astro when

### ISSUE THREAD

**Issue by IndependentCreator** [Fryuni/inox-tools#113]
Hi, thanks for creating these utilities! I'm trying to follow the example at https://inox-tools.vercel.app/astro-when 

I successfully ran:

`pnpm add -D @inox-tools/astro-when`

and I added these lines to astro.config.mjs: 

`import astroWhen from '@inox-tools/astro-when';`

`
export default defineConfig({
  integrations: [astroWhen()],
});`

But adding this line to middleware.ts doesn't work for me:

```import { whenAmI, When } from '@it-astro:when';```

(Cannot find module '@it-astro:when' or its corresponding type declarations.)

Any ideas as to what could be going wrong?

**Comment by Fryuni** [comment]
Hey @IndependentCreator, thanks for opening an issue!

We have a [test example](https://github.com/Fryuni/inox-tools/blob/main/examples/astro-when/src/middleware.ts) that seems to be the same as you described. I also tried on a brand new project, and it seems to work fine.

Can you share your full `astro.config.mjs` file?

**Comment by IndependentCreator** [comment]
> We have a [test example](https://github.com/Fryuni/inox-tools/blob/main/examples/astro-when/src/middleware.ts) that seems to be the same as you described. I also tried on a brand new project, and it seems to work fine.

Hmm I'm not sure what was going on with my setup, but I ended up refactoring my code and I no longer have a use case for astro when, so I think we can close this issue. Thanks for the quick response!

**Comment by Fryuni** [comment]
Okay!
