### ISSUE TITLE
Error in documentation for Astro sitemap extension

### ISSUE THREAD

**Issue by teinett** [Fryuni/inox-tools#42]
Page: https://inox-tools.vercel.app/sitemap-ext
Docs in source: https://github.com/Fryuni/inox-tools/blob/785f2433c8f02d2b83fc766df3b6a4ff12a205a4/docs/src/content/docs/sitemap-ext.md?plain=1#L53

Line 53: `sitemap(true); // opt-out`

I think for opt-out we should use `sitemap(false);`

**Comment by Fryuni** [comment]
Thank you!
